---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
        # Keep the container running
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            cpu: 30m        # Guaranteed 3% of a core to be scheduled
            memory: 64Mi
          limits:
            cpu: 100m       # Throttled if use more than 10% of a core
            memory: 128Mi


# kubectl apply -f busybox.yaml
# kubectl get pods -n development -o wide

# kubectl exec busybox-pod-name -- wget -O - pod-info-deployment-ip:3000
