--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-deployment
  namespace: development
  labels:
    app: pod-info
spec:
  replicas: 3
  selector:              # 1. The Controller's Selector
    matchLabels:
      app: pod-info
  template:              # 2. The Pod Template Blueprint
    metadata:
      labels:            # 3. Must match the selector above!
        app: pod-info
    spec:
      containers:
      - name: pod-info-container
        image: kimschles/pod-info-app:latest
        ports:
        - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP


# kubectl apply -f deployment.yaml
# kubectl get deployments -n development
# kubectl get pods -n development

# kubectl delete pod pod-name -n development
# kubectl describe pod pod-name -n development

# kubectl delete deployment deployment-name -n development
