--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-deployment
  namespace: development
  labels:
    app: pod-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      containers:
      - name: pod-info-container
        image: kimschles/pod-info-app:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:      # Container-level fine-grained hardening
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 3000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP


# snyk auth
# snyk iac test deployment.yaml
# [Medium] Container or Pod is running without root user control
# [Medium] Container does not drop all default capabilities
# [Medium] Container is running without privilege escalation control

# snyk iac test secure-deployment.yaml

# kubectl describe pod pod-name
# kubectl apply -f secure-deployment.yaml
# kubectl get pods -l app=pod-info -n development

# Verify Active Process Permissions (Runtime Test)
# kubectl exec -it pod-name -n development -- id
